steps:
  - label: ":eslint: JS Lint"
    command:
      - "yarn install"
      - "yarn lint:js"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

# This layer doesn't have a TypeScript linter. This comment is to remind TravisR to fix that.
#  - label: ":eslint: TS Lint"
#    command:
#      - "echo '--- Install js-sdk'"
#      - "./scripts/ci/install-deps.sh"
#      - "yarn lint:ts"
#    plugins:
#      - docker#v3.0.1:
#          image: "node:12"

  - label: ":eslint: Types Lint"
    command:
      - "yarn install"
      - "yarn lint:types"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: "🛠 Build"
    command:
      # TODO: This probably needs to be more sophisticated than "just install stuff"
      - "yarn install"
      - "yarn build"
    plugins:
      - docker#v3.0.1:
          image: "node:12"

  - label: ":karma: Tests"
    agents:
      # We use a medium sized instance instead of the normal small ones because
      # webpack loves to gorge itself on resources.
      queue: "medium"
    command:
      # Install chrome
      - "echo '--- Installing Chrome'"
      - "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -"
      - "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google.list'"
      - "apt-get update"
      - "apt-get install -y google-chrome-stable"
      # Run tests
      - "echo '--- Fetching Dependencies'"
      - "./scripts/fetch-develop.deps.sh --depth 1"
      - "yarn install"
      - "echo '+++ Running Tests'"
      - "yarn test"
    env:
      CHROME_BIN: "/usr/bin/google-chrome-stable"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
          propagate-environment: true

  - label: ":hammer: Package"
    command:
      - "echo '--- Fetching Dependencies'"
      - "./scripts/fetch-develop.deps.sh --depth 1"
      - "yarn install"
      - "echo '+++ Packaging'"
      - "./scripts/ci_package.sh"
    branches: "develop"
    artifact_paths: "dist/riot-*.tar.gz"
    plugins:
      - docker#v3.0.1:
          image: "node:10"

  - label: "🌐 i18n"
    command:
      - "echo '--- Fetching Dependencies'"
      - "./scripts/fetch-develop.deps.sh --depth 1"
      - "yarn install"
      - "echo '+++ Testing i18n output'"
      - "yarn diff-i18n"
    plugins:
      - docker#v3.0.1:
          image: "node:10"
