name: Release Process
on:
    workflow_dispatch:
        inputs:
            mode:
                description: What type of release
                required: true
                default: rc
                type: choice
                options:
                    - rc
                    - final
            matrix-react-sdk:
                description: React SDK version to use (current|X.Y.Z)
                required: false
                default: current
                type: string
            matrix-js-sdk:
                description: JS SDK version to use (current|X.Y.Z)
                required: false
                default: current
                type: string
concurrency: ${{ github.workflow }}
jobs:
    release:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-action.yml@develop
        secrets: inherit
        with:
            final: ${{ inputs.mode == 'final' }}
            include-changes: matrix-react-sdk
            gpg-fingerprint: ${{ vars.GPG_FINGERPRINT }}
            asset-path: dist/*.tar.gz
            expected-asset-count: 3
            dependencies: |
                matrix-react-sdk=${{ inputs.matrix-react-sdk }}
                matrix-js-sdk=${{ inputs.matrix-js-sdk }}
