name: Sync labels
on:
    workflow_dispatch: {}
    schedule:
        - cron: "0 1 * * *" # 1am every day
    push:
        branches:
            - develop
        paths:
            - .github/labels.yml
jobs:
    sync-labels:
        uses: vector-im/element-meta/.github/workflows/sync-labels.yml@develop
        with:
            LABELS: |
                vector-im/element-meta
                .github/labels.yml
            DELETE: true
            WET: false
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}
