name: Move X-Needs-Info into Need info column in the Issue triage board

on:
  issues:
    types: [labeled]
    
jobs:
  move_needs_info_issues:
    name: Move X-Needs-Info issues to Need info on triage board
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@219d384e03fa4b6460cd24f9f37d19eb033a4338
      with:
        action-token: ${{ secrets.GITHUB_TOKEN }}
        project-url: "https://github.com/vector-im/element-web/projects/27"
        column-name: "Need info"
        label-name: "X-Needs-Info"

  move_priority_design_issues:
    name: Move priority X-Needs-Design issues to Design project board
    runs-on: ubuntu-latest
    if: >
        contains(github.event.issue.labels.*.name, 'X-Needs-Design') &&
        (contains(github.event.issue.labels.*.name, 'O-Frequent') ||
         contains(github.event.issue.labels.*.name, 'O-Occasional')) &&
        (contains(github.event.issue.labels.*.name, 'S-Critical') ||
         contains(github.event.issue.labels.*.name, 'S-Major') ||
         contains(github.event.issue.labels.*.name, 'S-Minor'))
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@219d384e03fa4b6460cd24f9f37d19eb033a4338
        with:
          action-token: "${{ secrets.ELEMENT_BOT_TOKEN }}"
          project-url: "https://github.com/orgs/vector-im/projects/14"
          column-name: "📥 Inbox"
          label-name: "X-Needs-Design"

  move_spaces_issues:
    name: Move Spaces issues to Delight project board
    runs-on: ubuntu-latest
    if: >
        contains(github.event.issue.labels.*.name, 'A-Spaces') ||
        contains(github.event.issue.labels.*.name, 'A-Space-Settings') ||
        contains(github.event.issue.labels.*.name, 'A-Subspaces')
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@219d384e03fa4b6460cd24f9f37d19eb033a4338
        with:
          action-token: "${{ secrets.ELEMENT_BOT_TOKEN }}"
          project-url: "https://github.com/orgs/vector-im/projects/6"
          column-name: "📥 Inbox"
          label-name: "A-Spaces"
